# Generated by Django 4.2.16 on 2024-09-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_subject_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('title_status', models.CharField(max_length=100)),
                ('mileage', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=17)),
                ('lot', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
